server:
  port: 8080
spring:
  application:
    name: mybatisDemo
  datasource:
    username: dwb
    password: 123qwe
    url: jdbc:mysql://localhost:3306/localtest?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl